- name: copy file
  hosts: '{{ ENV }}'
  become: yes
  become_user: root
  vars:
    src_dir: '{{ src_dir }}'
    src_upstream: '{{ src_upstream }}'
 
  tasks:
   - name: sync nginx file
#     synchronize: src= {{ src_dir }}/ dest=/etc/nginx/{{ dest_dir }}
     synchronize: 
       src: "{{ src_dir }}"
       dest: /etc/nginx/
       rsync_opts:
         - "--exclude=.git"
         - "--exclude=.idea"
         - "--exclude=.gitignore"
         - "--exclude=upstream"
         
   - name: sync upstream file
     synchronize:
       src: "{{ src_upstream }}"
       dest: /etc/nginx/conf.d/
       rsync_opts:
         - "--exclude=.git"
         - "--exclude=.idea"
         - "--exclude=.gitignore"
   - command: /usr/sbin/nginx -t
     register: result
     ignore_errors: yes
   - name: error message
     debug: msg="{{result.stderr_lines}}"
   - command: /usr/sbin/nginx -t
     notify:
      - "reload Nginx on cenots6"
      - "reload Nginx on cenots7"
      
  handlers:
   - name: "reload Nginx on cenots6"
     command: service nginx restart
     when: ansible_distribution_major_version == '6'
     
   - name: "reload Nginx on cenots7"
     command: systemctl restart nginx.service
     when: ansible_distribution_major_version == '7'